title: Indo Membrane
baseURL: /
params:
  footer:
    content: '&copy; Indo Membrane 2019'
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: /images/logo-t-100.png
    nav_title: Perusahaan
    social_title: Layanan
    subscribe_content: Ikuti perkembangan terbaru kami.
    subscribe_title: Dapatkan update terbaru
    tagline: >-
      Indo Membrane membangun Negeri dengan segudang pengalaman secara
      profesional dengan harga terjangkau.
  header:
    has_nav: true
    logo_img: /images/logo-t-100.png
    title: Azimuth
    menu:
      actions:
        - label: Whatsapp
          url: /whatsapp
  palette: blue
disableKinds:
  - RSS
